### ISSUE TITLE
Rating component throws exception

### ISSUE THREAD

**Issue by rusco** [ZEISS/precise-ui#69] opened 2019-04-02 10:50 UTC
### Versions

Precise UI  0.5.0

### Description

Rating component throws error 

### Steps to Reproduce
1. navigate to the Rating component : 
https://precise-ui.io/#/Components/Rating

2. click on any star of the first rating component 

3. observe the output in the browsers console. 
	

**Expected behavior:** 

No exception

**Actual behavior:** 

An exception is thrown in my Chrome73/Win10 System:

bundle.48bfe287.js:47 Uncaught Error: An error occurred. See https://github.com/styled-components/styled-components/blob/master/src/utils/errors.md#12 for more information. Additional arguments: iXSaRS
    at new StyledComponentsError (bundle.48bfe287.js:12)
    at Keyframes.toString (bundle.48bfe287.js:12)
    at Array.join (<anonymous>)
    at Array.toString (<anonymous>)
    at ne (bundle.48bfe287.js:47)
    at oe (bundle.48bfe287.js:47)
    at Ce (bundle.48bfe287.js:47)
    at zh (bundle.48bfe287.js:47)
    at Th (bundle.48bfe287.js:47)
    at Zh (bundle.48bfe287.js:47)
	

**Environment details:**
Chrome 73, Win 10 64 bit 

### Possible Solution

Follow stacktrace to discover where an invalid argument is passed.

**Comment by FlorianRappl** [comment] 2019-04-02 12:52
This seems to be some kind of regression (can we write a test for this?). Can you have a look @kotielnikov? Thanks!

Thanks for the report @rusco !

**Comment by FlorianRappl** [comment] 2019-05-24 07:39
Fixed in the latest version 0.6!

**Closed by FlorianRappl** 2019-05-24 07:39 UTC
Labels: bug, component
